version: 0.0
os: linux
files:
  - source: /
    destination: /webapp
hooks:
  AfterInstall:
    - location: /Scripts/Install_package.sh
      timeout: 100
  ApplicationStart:
    - location: /Scripts/applicationstart.sh
      timeout: 100
