version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Package & Dependicies are getting installed"
      - npm -f install
      - echo "Packages have been installed"
      - echon "Storing Build Artifact to the Location"
artifacts:
  files:
    - '**/*'
  
